### NUMERICAL TRANSFORMATION

####  Standard Scalar

$$
z = \frac{x - \mu}{\sigma}
$$

In [2]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [4]:
x = np.array([
    [10],[20],[3],[4],[100],[63]
])
x

array([[ 10],
       [ 20],
       [  3],
       [  4],
       [100],
       [ 63]])

In [5]:
ss = StandardScaler()
x_new = ss.fit_transform(x)
x_new

array([[-0.6460193 ],
       [-0.36915389],
       [-0.8398251 ],
       [-0.81213855],
       [ 1.84576944],
       [ 0.8213674 ]])

### Mean is zero and Standard Deviation is 1 after performing Scaling

In [11]:
print(int(x_new.mean()))
print(round(x.mean(),2))

0
33.33


In [16]:
print(round(x.std(),2))
print(x_new.std())

36.12
0.9999999999999999


### MinMax Scalar

Range = [0,1]

$$
x_{\text{scaled}} = \frac{x - x_{\min}}{x_{\max} - x_{\min}}
$$

Which means transformed minimum x is 0 and maximum x is 1

In [23]:
from sklearn.preprocessing import MinMaxScaler

x = np.array([
    [10],[20],[30],[45],[34]
])
mm_scale = MinMaxScaler()
x_new = mm_scale.fit_transform(x)
print(x_new)

[[0.        ]
 [0.28571429]
 [0.57142857]
 [1.        ]
 [0.68571429]]


### They are sensitive to Outliers

In [22]:
x = np.array([
    [10],[20],[30],[40],[1000]
])
mm_scale = MinMaxScaler()
x_new = mm_scale.fit_transform(x)
print(x_new) # the outlier 1000 squeezed others to zero

[[0.        ]
 [0.01010101]
 [0.02020202]
 [0.03030303]
 [1.        ]]


### MaxAbsScalar

$$
x_{\text{scaled}}=\frac{x}{|x|_{\max}}
$$

In [27]:
from sklearn.preprocessing import MaxAbsScaler

x = np.array([[10],
              [20],
              [30],
              [40],
              [-50]])

scaler = MaxAbsScaler()

x_scaled = scaler.fit_transform(x)

print(x_scaled)

[[ 0.2]
 [ 0.4]
 [ 0.6]
 [ 0.8]
 [-1. ]]


### Functional Transformer

Constructs transformed features by applying user defined function

In [28]:
from sklearn.preprocessing import FunctionTransformer

In [30]:
x = np.array([
    [4],[16],[20],[10]
])
func_transform = FunctionTransformer(np.log2)
x_new = func_transform.fit_transform(x)
x_new

array([[2.        ],
       [4.        ],
       [4.32192809],
       [3.32192809]])

In [31]:
x = np.array([
    [4],[16],[20],[10]
])
func_transform = FunctionTransformer(np.sqrt)
x_new = func_transform.fit_transform(x)
x_new

array([[2.        ],
       [4.        ],
       [4.47213595],
       [3.16227766]])

## Polynomial transformations

### Does explicit feature Uplifting

#### Original Feature Vector

$$
X = \begin{bmatrix}
x_1 & x_2
\end{bmatrix}
$$

#### After Polynomial Transformation (Degree = 2)

$$
\phi(X)=
\begin{bmatrix}
1,\;
x_1,\;
x_2,\;
x_1^2,\;
x_1x_2,\;
x_2^2
\end{bmatrix}
$$

In [32]:
from sklearn.preprocessing import PolynomialFeatures

In [34]:
x = np.array([
    [4,10],[2,1],[5,6],[9,0]
])

uplift = PolynomialFeatures(degree=2)
x_new = uplift.fit_transform(x)
x_new

array([[  1.,   4.,  10.,  16.,  40., 100.],
       [  1.,   2.,   1.,   4.,   2.,   1.],
       [  1.,   5.,   6.,  25.,  30.,  36.],
       [  1.,   9.,   0.,  81.,   0.,   0.]])

In [35]:
uplift = PolynomialFeatures(degree=3)
x_new = uplift.fit_transform(x)
x_new

array([[   1.,    4.,   10.,   16.,   40.,  100.,   64.,  160.,  400.,
        1000.],
       [   1.,    2.,    1.,    4.,    2.,    1.,    8.,    4.,    2.,
           1.],
       [   1.,    5.,    6.,   25.,   30.,   36.,  125.,  150.,  180.,
         216.],
       [   1.,    9.,    0.,   81.,    0.,    0.,  729.,    0.,    0.,
           0.]])